# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- development

pr: none

name: $(Rev:r)

variables:
  appBuildNumber: $(Build.BuildNumber)
  outputDir: "./app/build/outputs/apk/"
  debugDir: "debug/"

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  displayName: 'Assemble Debug'
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'assembleDebug'

- script: |
    mv $(outputDir)$(debugDir)app-debug.apk $(outputDir)$(debugDir)app-debug-$(appBuildNumber).apk
    mv $(outputDir)$(devDir)app-debug-$(appBuildNumber).apk $(outputDir)
  displayName: 'Rename Generated Artifacts'


- task: CopyFiles@2
  displayName: 'Copy Generated Artifacts'
  condition: succeeded()
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Generated Artifacts'
  condition: succeeded()
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'APKs'
